version: "3.7"

services:
  nginx:
    image: "nginx:latest"
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - "./nginx.env"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - "./ssl:/etc/nginx/ssl"
    restart: "unless-stopped"
